server:
  port: 8000
  servlet:
    encoding:
      charset: UTF-8
      force: true
      force-response: true

logging:
  level:
    root: INFO
  file:
    name: /app/log/gateway.log

spring:
  application:
    name: gateway-service
  jwt:
    secret: ${JWT_SECRET_KEY}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user/**
        - id: m-service
          uri: lb://m-service
          predicates:
            - Path=/api/v1/m/**
        - id: category-service
          uri: lb://category-service
          predicates:
            - Path=/api/v1/category/**
        - id: en-service
          uri: lb://en-service
          predicates:
            - Path=/api/v1/en/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka

springdoc:
  swagger-ui:
    urls:
      - name: User 서비스
        url: https://nansan.site/api/v1/user/v3/api-docs
      - name: BASA-M 서비스
        url: https://nansan.site/api/v1/m/v3/api-docs
      - name: Category 서비스
        url: https://nansan.site/api/v1/category/v3/api-docs
      - name: BASA-EN 서비스
        url: https://nansan.site/api/v1/en/v3/api-docs
    use-root-path: true
